### ISSUE TITLE
License please?

### ISSUE THREAD

**Issue by dalb8** [makiftutuncu/eshotroid-legacy#1]
It's a nice app, would be nice to publish on f-droid.org, but there needs to be an overall license.

**Comment by makiftutuncu** [comment]
I believe GPLv3 is OK and I added a license file to the root of my repository. :)

Thanks.

https://github.com/mehmetakiftutuncu/eshotroid/blob/master/LICENSE.txt

**Comment by dalb8** [comment]
Perfect thanks! I'll see to it to that it gets there, but it could take a few weeks. Donation items like Paypal, Bitcoin or Flattr are accepted.

**Comment by dalb8** [comment]
Oh, I forgot, they'd appreciate it if you could tag releases as it makes it easier to keep the app updated and accurate.
